//! Raw, auto-generated bindings to the cpdb-libs C API.
//!
//! Generated by `bindgen` from the headers listed in `include/wrapper.h`.
//! Everything here is `unsafe` and the C symbols may be renamed, removed,
//! or relayed between upstream releases — depend on the higher-level
//! modules (`frontend`, `printer`, ...) for stable Rust APIs.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(missing_docs)]

include!(concat!(env!("OUT_DIR"), "/cpdb_sys.rs"));
