//! # D-Bus interface proxy for: `org.openprinting.PrintBackend`
//!
//! This code was generated by `zbus-xmlgen` `5.3.1` from D-Bus introspection data.
//! Source: `org.openprinting.Backend.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.openprinting.PrintBackend", assume_defaults = true)]
pub trait PrintBackend {
    /// GetAllOptions method
    #[allow(clippy::type_complexity)]
    #[allow(clippy::type_complexity)]
    fn get_all_options(
        &self,
        printer_id: &str,
    ) -> zbus::Result<(
        i32,
        Vec<(String, String, String, i32, Vec<(String,)>)>,
        i32,
        Vec<(String, i32, i32, i32, Vec<(i32, i32, i32, i32)>)>,
    )>;

    /// GetAllPrinters method
    fn get_all_printers(&self) -> zbus::Result<(i32, Vec<(zbus::zvariant::OwnedValue,)>)>;

    /// GetAllTranslations method
    fn get_all_translations(
        &self,
        printer_id: &str,
        locale: &str,
    ) -> zbus::Result<std::collections::HashMap<String, String>>;

    /// GetBackendName method
    fn get_backend_name(&self) -> zbus::Result<String>;

    /// GetFilteredPrinterList method
    fn get_filtered_printer_list(&self) -> zbus::Result<(i32, Vec<(zbus::zvariant::OwnedValue,)>)>;

    /// doListing method
    #[zbus(name = "doListing")]
    fn do_listing(&self, is_listed: bool) -> zbus::Result<()>;

    /// getChoiceTranslation method
    #[zbus(name = "getChoiceTranslation")]
    fn get_choice_translation(
        &self,
        printer_name: &str,
        option_name: &str,
        choice_name: &str,
        locale: &str,
    ) -> zbus::Result<String>;

    /// getDefaultPrinter method
    #[zbus(name = "getDefaultPrinter")]
    fn get_default_printer(&self) -> zbus::Result<String>;

    /// getGroupTranslation method
    #[zbus(name = "getGroupTranslation")]
    fn get_group_translation(
        &self,
        printer_name: &str,
        group_name: &str,
        locale: &str,
    ) -> zbus::Result<String>;

    /// getOptionTranslation method
    #[zbus(name = "getOptionTranslation")]
    fn get_option_translation(
        &self,
        printer_name: &str,
        option_name: &str,
        locale: &str,
    ) -> zbus::Result<String>;

    /// getPrinterState method
    #[zbus(name = "getPrinterState")]
    fn get_printer_state(&self, printer_id: &str) -> zbus::Result<String>;

    /// isAcceptingJobs method
    #[zbus(name = "isAcceptingJobs")]
    fn is_accepting_jobs(&self, printer_id: &str) -> zbus::Result<bool>;

    /// keepAlive method
    #[zbus(name = "keepAlive")]
    fn keep_alive(&self) -> zbus::Result<()>;

    /// ping method
    #[zbus(name = "ping")]
    fn ping(&self, printer_id: &str) -> zbus::Result<()>;

    /// printFd method
    #[zbus(name = "printFd")]
    fn print_fd(
        &self,
        printer_id: &str,
        num_settings: i32,
        settings: &[&(&str, &str)],
        title: &str,
    ) -> zbus::Result<(String, zbus::zvariant::OwnedFd)>;

    /// printSocket method
    #[zbus(name = "printSocket")]
    fn print_socket(
        &self,
        printer_id: &str,
        num_settings: i32,
        settings: &[&(&str, &str)],
        title: &str,
    ) -> zbus::Result<(String, String)>;

    /// replace method
    #[zbus(name = "replace")]
    fn replace(&self, previous_dialog_id: &str) -> zbus::Result<()>;

    /// showRemotePrinters method
    #[zbus(name = "showRemotePrinters")]
    fn show_remote_printers(&self, is_visible: bool) -> zbus::Result<()>;

    /// showTemporaryPrinters method
    #[zbus(name = "showTemporaryPrinters")]
    fn show_temporary_printers(&self, is_visible: bool) -> zbus::Result<()>;

    /// PrinterAdded signal
    #[zbus(signal)]
    fn printer_added(
        &self,
        printer_id: &str,
        printer_name: &str,
        printer_info: &str,
        printer_location: &str,
        printer_make_and_model: &str,
        printer_is_accepting_jobs: bool,
        printer_state: &str,
        backend_name: &str,
    ) -> zbus::Result<()>;

    /// PrinterRemoved signal
    #[zbus(signal)]
    fn printer_removed(&self, printer_id: &str, backend_name: &str) -> zbus::Result<()>;

    /// PrinterStateChanged signal
    #[zbus(signal)]
    fn printer_state_changed(
        &self,
        printer_id: &str,
        printer_state: &str,
        printer_is_accepting_jobs: bool,
        backend_name: &str,
    ) -> zbus::Result<()>;
}
